// --------------------------------------------------------------------------------------------------------------------
// <copyright file="ConsoleAbstractionBase.cs" company="Naos Project">
//   Copyright (c) Naos Project 2019. All rights reserved.
// </copyright>
// <auto-generated>
//   Sourced from NuGet package. Will be overwritten with package update except in 'Naos.Bootstrapper.Recipes.Core.Test' source.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

namespace Naos.Bootstrapper
{
    using System;
    using FakeItEasy;
    using OBeautifulCode.Type.Recipes;

    /// <summary>
    /// Custom exception for when a test fails.
    /// Implements the <see cref="System.Exception" />
    /// </summary>
    /// <seealso cref="System.Exception" />
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [System.CodeDom.Compiler.GeneratedCode("Naos.Bootstrapper.Recipes.Core.Test", "See package version.")]
    public class TestFailedException : Exception
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TestFailedException"/> class.
        /// </summary>
        /// <param name="testType">Type of the test to run.</param>
        public TestFailedException(
            Type testType)
            : base(FormattableString.Invariant($"One or more tests in '{testType.ToStringReadable(ToStringReadableOptions.IncludeNamespace)}' failed, see output for details."))
        {
        }
    }
}