// --------------------------------------------------------------------------------------------------------------------
// <copyright file="RepresentationSystemDummyFactory.cs" company="OBeautifulCode">
//   Copyright (c) OBeautifulCode 2018. All rights reserved.
// </copyright>
// <auto-generated>
//   Sourced from NuGet package. Will be overwritten with package update except in OBeautifulCode.Representation.System.Test source.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

namespace OBeautifulCode.Representation.System.Test
{
    using System;
    using FakeItEasy;
    using global::System;
    using OBeautifulCode.AutoFakeItEasy;

    /// <summary>
    /// A Dummy Factory for types in <see cref="OBeautifulCode.Representation.System"/>.
    /// </summary>
#if !OBeautifulCodeRepresentationSolution
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [global::System.CodeDom.Compiler.GeneratedCode("OBeautifulCode.Compression.Test", "See package version number")]
    internal
#else
    public
#endif
    class RepresentationSystemDummyFactory : DefaultRepresentationSystemDummyFactory
    {
        public RepresentationSystemDummyFactory()
        {
            AutoFixtureBackedDummyFactory.AddDummyCreator(
                () =>
                {
                    // TypeDummyFactory will return a real, loaded type.
                    var result = A.Dummy<Type>().ToRepresentation();

                    return result;
                });
        }
    }
}
