// --------------------------------------------------------------------------------------------------------------------
// <auto-generated>
//   Generated using OBeautifulCode.CodeGen.ModelObject (1.0.199.0)
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

namespace Naos.Database.Domain
{
    using global::System;
    using global::System.CodeDom.Compiler;
    using global::System.Collections.Concurrent;
    using global::System.Collections.Generic;
    using global::System.Collections.ObjectModel;
    using global::System.Diagnostics.CodeAnalysis;
    using global::System.Globalization;
    using global::System.Linq;

    using global::OBeautifulCode.Cloning.Recipes;
    using global::OBeautifulCode.Equality.Recipes;
    using global::OBeautifulCode.Type;
    using global::OBeautifulCode.Type.Recipes;

    using static global::System.FormattableString;

    [Serializable]
    public partial class RecordHandlingAvailableEvent : IModel<RecordHandlingAvailableEvent>
    {
        /// <summary>
        /// Determines whether two objects of type <see cref="RecordHandlingAvailableEvent"/> are equal.
        /// </summary>
        /// <param name="left">The object to the left of the equality operator.</param>
        /// <param name="right">The object to the right of the equality operator.</param>
        /// <returns>true if the two items are equal; otherwise false.</returns>
        public static bool operator ==(RecordHandlingAvailableEvent left, RecordHandlingAvailableEvent right)
        {
            if (ReferenceEquals(left, right))
            {
                return true;
            }

            if (ReferenceEquals(left, null) || ReferenceEquals(right, null))
            {
                return false;
            }

            var result = left.Equals(right);

            return result;
        }

        /// <summary>
        /// Determines whether two objects of type <see cref="RecordHandlingAvailableEvent"/> are not equal.
        /// </summary>
        /// <param name="left">The object to the left of the equality operator.</param>
        /// <param name="right">The object to the right of the equality operator.</param>
        /// <returns>true if the two items are not equal; otherwise false.</returns>
        public static bool operator !=(RecordHandlingAvailableEvent left, RecordHandlingAvailableEvent right) => !(left == right);

        /// <inheritdoc />
        public bool Equals(RecordHandlingAvailableEvent other)
        {
            if (ReferenceEquals(this, other))
            {
                return true;
            }

            if (ReferenceEquals(other, null))
            {
                return false;
            }

            var result = this.TimestampUtc.IsEqualTo(other.TimestampUtc)
                      && this.Details.IsEqualTo(other.Details, StringComparer.Ordinal)
                      && this.Concern.IsEqualTo(other.Concern, StringComparer.Ordinal)
                      && this.InternalRecordId.IsEqualTo(other.InternalRecordId)
                      && this.RecordToHandle.IsEqualTo(other.RecordToHandle);

            return result;
        }

        /// <inheritdoc />
        public override bool Equals(object obj) => this == (obj as RecordHandlingAvailableEvent);

        /// <inheritdoc />
        public override int GetHashCode() => HashCodeHelper.Initialize()
            .Hash(this.TimestampUtc)
            .Hash(this.Details)
            .Hash(this.Concern)
            .Hash(this.InternalRecordId)
            .Hash(this.RecordToHandle)
            .Value;

        /// <inheritdoc />
        public new RecordHandlingAvailableEvent DeepClone() => (RecordHandlingAvailableEvent)this.DeepCloneInternal();

        /// <inheritdoc />
        [SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        protected override EventBase DeepCloneInternal()
        {
            var result = new RecordHandlingAvailableEvent(
                                 this.InternalRecordId.DeepClone(),
                                 this.Concern?.DeepClone(),
                                 this.RecordToHandle?.DeepClone(),
                                 this.TimestampUtc.DeepClone(),
                                 this.Details?.DeepClone());

            return result;
        }

        /// <inheritdoc />
        [SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        public override string ToString()
        {
            var result = Invariant($"Naos.Database.Domain.RecordHandlingAvailableEvent: TimestampUtc = {this.TimestampUtc.ToString(CultureInfo.InvariantCulture) ?? "<null>"}, Details = {this.Details?.ToString(CultureInfo.InvariantCulture) ?? "<null>"}, Concern = {this.Concern?.ToString(CultureInfo.InvariantCulture) ?? "<null>"}, InternalRecordId = {this.InternalRecordId.ToString(CultureInfo.InvariantCulture) ?? "<null>"}, RecordToHandle = {this.RecordToHandle?.ToString() ?? "<null>"}.");

            return result;
        }
    }
}