// --------------------------------------------------------------------------------------------------------------------
// <auto-generated>
//   Generated using OBeautifulCode.CodeGen.ModelObject (1.0.0.0)
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

namespace OBeautifulCode.Type.Test
{
    using global::System;
    using global::System.CodeDom.Compiler;
    using global::System.Collections.Concurrent;
    using global::System.Collections.Generic;
    using global::System.Collections.ObjectModel;
    using global::System.Diagnostics.CodeAnalysis;

    using global::FakeItEasy;

    using global::OBeautifulCode.AutoFakeItEasy;
    using global::OBeautifulCode.Math.Recipes;
    using global::OBeautifulCode.Type;

    /// <summary>
    /// The default (code generated) Dummy Factory.
    /// Derive from this class to add any overriding or custom registrations.
    /// </summary>
    [ExcludeFromCodeCoverage]
    [GeneratedCode("OBeautifulCode.CodeGen.ModelObject", "1.0.0.0")]
#if !OBeautifulCodeTypeSolution
    internal
#else
    public
#endif
    abstract class DefaultTypeDummyFactory : IDummyFactory
    {
        public DefaultTypeDummyFactory()
        {
            AutoFixtureBackedDummyFactory.AddDummyCreator(
                () => new ThrowOpExecutionAbortedExceptionOp(
                                 A.Dummy<string>()));

            AutoFixtureBackedDummyFactory.AddDummyCreator(
                () => new ThrowOpExecutionAbortedExceptionOp<Version>(
                                 A.Dummy<string>()));

            AutoFixtureBackedDummyFactory.AddDummyCreator(
                () => new GetProtocolOp(
                                 A.Dummy<IOperation>(),
                                 A.Dummy<MissingProtocolStrategy>()));

            AutoFixtureBackedDummyFactory.AddDummyCreator(
                () =>
                {
                    var availableTypes = new[]
                    {
                        typeof(ExecuteOpRequestedEvent<Version, GetProtocolOp>),
                        typeof(ExecuteOpRequestedEvent<GetProtocolOp>),
                        typeof(NullEvent),
                        typeof(NullEvent<Version>)
                    };

                    var randomIndex = ThreadSafeRandom.Next(0, availableTypes.Length);

                    var randomType = availableTypes[randomIndex];

                    var result = (EventBase)AD.ummy(randomType);

                    return result;
                });

            AutoFixtureBackedDummyFactory.AddDummyCreator(
                () =>
                {
                    var availableTypes = new[]
                    {
                        typeof(ExecuteOpRequestedEvent<Version, GetProtocolOp>),
                        typeof(NullEvent<Version>)
                    };

                    var randomIndex = ThreadSafeRandom.Next(0, availableTypes.Length);

                    var randomType = availableTypes[randomIndex];

                    var result = (EventBase<Version>)AD.ummy(randomType);

                    return result;
                });

            AutoFixtureBackedDummyFactory.AddDummyCreator(
                () => new ExecuteOpRequestedEvent<Version, GetProtocolOp>(
                                 A.Dummy<Version>(),
                                 A.Dummy<GetProtocolOp>(),
                                 A.Dummy<DateTime>(),
                                 A.Dummy<string>()));

            AutoFixtureBackedDummyFactory.AddDummyCreator(
                () => new ExecuteOpRequestedEvent<GetProtocolOp>(
                                 A.Dummy<GetProtocolOp>(),
                                 A.Dummy<DateTime>(),
                                 A.Dummy<string>()));

            AutoFixtureBackedDummyFactory.AddDummyCreator(
                () => new NullEvent(
                                 A.Dummy<DateTime>()));

            AutoFixtureBackedDummyFactory.AddDummyCreator(
                () => new NullEvent<Version>(
                                 A.Dummy<Version>(),
                                 A.Dummy<DateTime>()));

            AutoFixtureBackedDummyFactory.AddDummyCreator(
                () => new NamedValue<Version>(
                                 A.Dummy<string>(),
                                 A.Dummy<Version>()));

            AutoFixtureBackedDummyFactory.AddDummyCreator(
                () => new NullReturningOp<Version>());

            AutoFixtureBackedDummyFactory.AddDummyCreator(
                () => new TestVoidOp(A.Dummy<string>()));

            AutoFixtureBackedDummyFactory.AddDummyCreator(
                () => new TestReturningOp<Version>(A.Dummy<string>()));

            AutoFixtureBackedDummyFactory.AddDummyCreator(
                () => new NullVoidOp());

            AutoFixtureBackedDummyFactory.AddDummyCreator(
                () => new GetConstValueOp<Version>(A.Dummy<Version>()));

            AutoFixtureBackedDummyFactory.AddDummyCreator(
                () =>
                {
                    var availableTypes = new[]
                    {
                        typeof(ThrowOpExecutionAbortedExceptionOp),
                        typeof(ThrowOpExecutionAbortedExceptionOp<Version>),
                        typeof(GetProtocolOp),
                        typeof(NullReturningOp<Version>),
                        typeof(TestReturningOp<Version>),
                        typeof(TestVoidOp),
                        typeof(NullVoidOp),
                        typeof(GetConstValueOp<Version>),
                    };

                    var randomIndex = ThreadSafeRandom.Next(0, availableTypes.Length);

                    var randomType = availableTypes[randomIndex];

                    var result = (OperationBase)AD.ummy(randomType);

                    return result;
                });

            AutoFixtureBackedDummyFactory.AddDummyCreator(
                () =>
                {
                    var availableTypes = new[]
                    {
                        typeof(ThrowOpExecutionAbortedExceptionOp<Version>),
                        typeof(NullReturningOp<Version>),
                        typeof(TestReturningOp<Version>),
                        typeof(GetConstValueOp<Version>),
                    };

                    var randomIndex = ThreadSafeRandom.Next(0, availableTypes.Length);

                    var randomType = availableTypes[randomIndex];

                    var result = (ReturningOperationBase<Version>)AD.ummy(randomType);

                    return result;
                });

            AutoFixtureBackedDummyFactory.AddDummyCreator(
                () =>
                {
                    var availableTypes = new[]
                    {
                        typeof(ThrowOpExecutionAbortedExceptionOp),
                        typeof(TestVoidOp),
                        typeof(NullVoidOp)
                    };

                    var randomIndex = ThreadSafeRandom.Next(0, availableTypes.Length);

                    var randomType = availableTypes[randomIndex];

                    var result = (VoidOperationBase)AD.ummy(randomType);

                    return result;
                });

            AutoFixtureBackedDummyFactory.AddDummyCreator(
                () => new UtcDateTimeRangeInclusive(
                                 A.Dummy<DateTime>(),
                                 A.Dummy<DateTime>()));
        }

        /// <inheritdoc />
        public Priority Priority => new FakeItEasy.Priority(1);

        /// <inheritdoc />
        public bool CanCreate(Type type)
        {
            return false;
        }

        /// <inheritdoc />
        public object Create(Type type)
        {
            return null;
        }
    }
}